apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka-producer-deployment
  annotations:
    commitID: "c88e0ebc7097eb02b19e9a20715388205d2f4b03"
spec:
  replicas: 2s
  selector:
    matchLabels:
      app: api-kafka-producer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-kafka-producer
    spec:
      containers:
        - name: api-kafka-producer
          image: 'xavelo/api-kafka-producer:c88e0ebc7097eb02b19e9a20715388205d2f4b03'
          ports:
            - containerPort: 80
